spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?user=root&password=1460088689
    username: root
    password: 1460088689
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
#    database-platform: org.hibernate.dialect.MYSQL5Dialect

  elasticsearch:
    rest:
      uris: 112.198.251.106:9200

#SSL config
  mail:
    port: 465
    protocol: smtp
    default-encoding: UTF-8
#    properties: {
#      mail.smtp.auth: true,
#      mail.smtp.starttls.enable: true,
#      mail.smtp.starttls.required: true,
#
#      mail.smtp.ssl.enable: true,
#      mail.smtp.socketFactory.port: 465,
#      smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory,
#      smtp.socketFactory.fallback: false,
#    }
    host: smtp.163.com
    username: z53482947@163.com
    password: dhdied
#  main:
#    allow-bean-definition-overriding: true

logging:
  level:
    root: warn
    com.loocc: info
  file: log/blog-pro.log

icp:
  beian: 蜀ICP备20002977号


server:
  port: 8080
