spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tt_blog?serverTimezone=Asia/Shanghai&useUnicode=false
    username: root
    password: 1460088689
  mvc:
    view:
      suffix: .html
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  level:
    root: info
    com.lrm: debug

  file: log/blog-dev.log

  elasticsearch:
    rest:
      uris: 123.134.12.176:9200

  main:
    allow-bean-definition-overriding: true

  data:
    elasticsearch:
      repositories:
        enabled: true

  mail:
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    username: z38223937@163.com
    password: Zdd239    #授权码，不是邮箱密码
    host: smtp.163.com


#elasticsearch.host: 116.34.119.115:9200

server:
  port: 8081
  